/*
	Do not edit this file directly. This file defines the assembly metadata and should not be modified
	at any case except if it is needed.
*/

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: System.Reflection.AssemblyCompanyAttribute("© MDCDI1315. https://github.com/mdcdi1315/mdcframework")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("© MDCDI1315. All Rights Reserved.")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Portable Application Development Framework")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.5.5.03")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.5.5.03 Built by: © MDCDI1315.")]
[assembly: System.Reflection.AssemblyProductAttribute("MDC Application Framework , Version 1.5.5.0 Minor 3")]
[assembly: System.Reflection.AssemblyTitleAttribute(".NET Application Development Framework")]
[assembly: System.Reflection.AssemblyVersionAttribute("4.4.0.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]