/*
	Do not edit this file directly. This file defines the assembly metadata and should not be modified
	at any case except if it is needed.
*/

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: System.Reflection.AssemblyCompanyAttribute($"© MDCDI1315. {mdcdi1315.SourceLink}")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute(mdcdi1315.Copyright)]
[assembly: System.Reflection.AssemblyDescriptionAttribute(mdcdi1315.Description)]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.5.5.04")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.5.5.04 Built by: © MDCDI1315.")]
[assembly: System.Reflection.AssemblyProductAttribute($"{mdcdi1315.Product} , Version 1.5.5.0 Minor 4")]
[assembly: System.Reflection.AssemblyTitleAttribute("\".NET Framework 4.8\" Application Development Framework")]
[assembly: System.Reflection.AssemblyVersionAttribute("4.4.0.0")]
[assembly: DefaultDllImportSearchPaths(DllImportSearchPath.System32 | DllImportSearchPath.AssemblyDirectory)]
[assembly: AssemblyMetadata("mdcdi1315" , "http://github.com/mdcdi1315")]
[assembly: AssemblyMetadata("Repository URL" , mdcdi1315.SourceLink)]
[assembly: AssemblyMetadata("RELEASECHANNEL" , "TRUE")]
[assembly: AssemblyMetadata("FrameworkDisplayName (FDN Internal)" , ".NET Framework 4.8")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]