# This script file moves the the build artifacts to the top-level bin directory.
[IfDirExists:.\bin\Debug\net48\] { [Move:.\bin\Debug\net48\$..\..\bin\NET48] }
[IfDirExists:.\bin\Debug\net70-windows10.0.19041.0\] { [Move:.\bin\Debug\net70-windows10.0.19041.0\$..\..\bin\NET70] }
[IfDirExists:.\bin\Release\net48\] { [Move:.\bin\Release\net48\$..\..\bin\Release\NET48] }
[IfDirExists:.\bin\Release\net70-windows10.0.19041.0\] { [Move:.\bin\Release\net70-windows10.0.19041.0\$..\..\bin\Release\NET70] }
[IfDirExists:.\bin\Release\net70\] { [Move:.\bin\Release\net70\$..\..\bin\Release\NET70-NW] }
[IfDirExists:.\bin\Debug\net70\] { [Move:.\bin\Debug\net70\$..\..\bin\NET70-NW] }