/*
 *  © MDCDI1315. Do not edit this file unless really required to do.
 *  This file defines the System.Resources.Extensions assembly properties
 *  and if modified can cause problems related to assembly loading.
 */


using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: NeutralResourcesLanguage("en-US")]
[assembly: AssemblyDefaultAlias("System.Resources.Extensions")]
[assembly: AssemblyCompanyAttribute($"© MDCDI1315. {mdcdi1315.SourceLink}")]
[assembly: AssemblyCopyrightAttribute(mdcdi1315.Copyright)]
[assembly: AssemblyTitle("System.Resources.Extensions DLL For MDCFR Library - Custom Build")]
[assembly: AssemblyDescriptionAttribute("Provides the overriding solution of normal System.Resources.Extensions" + 
    " DLL but linked with MDCFR so as to gain the benefits of one single library.")]
[assembly: AssemblyFileVersionAttribute("8.0.23.28008")]
[assembly: AssemblyInformationalVersionAttribute($"{mdcdi1315.VersionNumber} Built by: © MDCDI1315.")]
[assembly: AssemblyProductAttribute($"{mdcdi1315.Product} , System.Resources.Extensions Custom Overriding Library")]
[assembly: AssemblyAlgorithmId(System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384)]
[assembly: AssemblyTrademark(mdcdi1315.Trademark)]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyVersionAttribute("8.0.0.0")]
[assembly: AssemblyMetadataAttribute(mdcdi1315.Author, mdcdi1315.AuthorLinkGitHub)]
[assembly: AssemblyMetadataAttribute("Repository URL", mdcdi1315.SourceLink)]
#if DEBUG
    [assembly: AssemblyConfigurationAttribute("Debug")]
#else
    [assembly: AssemblyConfigurationAttribute("Release")]
#endif
