/*
	Do not edit this file directly. This file defines the assembly metadata and should not be modified
	at any case except if it is needed.
*/

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompanyAttribute($"© MDCDI1315. {mdcdi1315.SourceLink}")]
[assembly: AssemblyCopyrightAttribute(mdcdi1315.Copyright)]
[assembly: AssemblyDescriptionAttribute(mdcdi1315.Description)]
[assembly: AssemblyFileVersionAttribute(mdcdi1315.VersionNumber)]
[assembly: AssemblyInformationalVersionAttribute($"{mdcdi1315.VersionNumber} Built by: © MDCDI1315.")]
[assembly: AssemblyProductAttribute($"{mdcdi1315.Product} , Version 1.0.0.0 Minor 1")]
[assembly: AssemblyVersionAttribute("4.4.0.0")]
[assembly: DefaultDllImportSearchPathsAttribute((DllImportSearchPath) mdcdi1315.DefaultDllImportSearchPathConst)]
[assembly: AssemblyMetadataAttribute(mdcdi1315.Author , mdcdi1315.AuthorLinkGitHub)]
[assembly: AssemblyMetadataAttribute("Repository URL" , mdcdi1315.SourceLink)]
#if DEBUG
    [assembly: AssemblyTitleAttribute("\".NET Framework 4.8\" Application Development Framework Deprecated Component: HTTPLIB (Debug Flavor)")]
    [assembly: AssemblyConfigurationAttribute("Debug")]
    [assembly: AssemblyMetadataAttribute("RELEASECHANNEL", "FALSE")]
    [assembly: AssemblyMetadataAttribute("DEBUGCHANNEL", "TRUE")]
#else
    [assembly: AssemblyTitleAttribute("\".NET Framework 4.8\" Application Development Framework Deprecated Component: HTTPLIB")]
    [assembly: AssemblyConfigurationAttribute("Release")]
    [assembly: AssemblyMetadataAttribute("RELEASECHANNEL" , "TRUE")]
    [assembly: AssemblyMetadataAttribute("DEBUGCHANNEL" , "FALSE")]
#endif
[assembly: AssemblyMetadataAttribute("FrameworkDisplayName (FDN Internal)", ".NET Core CLR 7.0.5")]
[assembly: AssemblyMetadataAttribute("CompatibilityNotes", mdcdi1315.CompatNotes)]
[assembly: AssemblyMetadata("ComponentDesc" , "Some of the underlying API used in HTTPLIB is deprecated in Core CLR 7.")]
[assembly: AssemblyAlgorithmId(System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384)]
[assembly: AssemblyTrademark(mdcdi1315.Trademark)]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
