//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDCFR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDCFR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of bounds:.
        /// </summary>
        internal static string Arg_ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("Arg_ArgumentOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of elements in source vector is greater than the destination array.
        /// </summary>
        internal static string Arg_ElementsInSourceIsGreaterThanDestination {
            get {
                return ResourceManager.GetString("Arg_ElementsInSourceIsGreaterThanDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least {0} element(s) are expected in the parameter &quot;{1}&quot;..
        /// </summary>
        internal static string Arg_InsufficientNumberOfElements {
            get {
                return ResourceManager.GetString("Arg_InsufficientNumberOfElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given key &apos;{0}&apos; was not present in the dictionary..
        /// </summary>
        internal static string Arg_KeyNotFoundWithKey {
            get {
                return ResourceManager.GetString("Arg_KeyNotFoundWithKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method was called with a null array argument..
        /// </summary>
        internal static string Arg_NullArgumentNullRef {
            get {
                return ResourceManager.GetString("Arg_NullArgumentNullRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ResourceReader class does not know how to read this version of .resources files. Expected version: {0}  This file: {1}.
        /// </summary>
        internal static string Arg_ResourceFileUnsupportedVersion {
            get {
                return ResourceManager.GetString("Arg_ResourceFileUnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified type is not supported.
        /// </summary>
        internal static string Arg_TypeNotSupported {
            get {
                return ResourceManager.GetString("Arg_TypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format specifier was invalid..
        /// </summary>
        internal static string Argument_BadFormatSpecifier {
            get {
                return ResourceManager.GetString("Argument_BadFormatSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters following the format symbol must be a number of {0} or less..
        /// </summary>
        internal static string Argument_CannotParsePrecision {
            get {
                return ResourceManager.GetString("Argument_CannotParsePrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a supported code page..
        /// </summary>
        internal static string Argument_CodepageNotSupported {
            get {
                return ResourceManager.GetString("Argument_CodepageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination is too short..
        /// </summary>
        internal static string Argument_DestinationTooShort {
            get {
                return ResourceManager.GetString("Argument_DestinationTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must complete Convert() operation or call Encoder.Reset() before calling GetBytes() or GetByteCount(). Encoder &apos;{0}&apos; fallback &apos;{1}&apos;..
        /// </summary>
        internal static string Argument_EncoderFallbackNotEmpty {
            get {
                return ResourceManager.GetString("Argument_EncoderFallbackNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output byte buffer is too small to contain the encoded data, encoding &apos;{0}&apos; fallback &apos;{1}&apos;..
        /// </summary>
        internal static string Argument_EncodingConversionOverflowBytes {
            get {
                return ResourceManager.GetString("Argument_EncodingConversionOverflowBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output char buffer is too small to contain the decoded characters, encoding &apos;{0}&apos; fallback &apos;{1}&apos;..
        /// </summary>
        internal static string Argument_EncodingConversionOverflowChars {
            get {
                return ResourceManager.GetString("Argument_EncodingConversionOverflowChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;G&apos; format combined with a precision is not supported..
        /// </summary>
        internal static string Argument_GWithPrecisionNotSupported {
            get {
                return ResourceManager.GetString("Argument_GWithPrecisionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String contains invalid Unicode code points..
        /// </summary>
        internal static string Argument_InvalidCharSequenceNoIndex {
            get {
                return ResourceManager.GetString("Argument_InvalidCharSequenceNoIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use type &apos;{0}&apos;. Only value types without pointers or references are supported..
        /// </summary>
        internal static string Argument_InvalidTypeWithPointersNotSupported {
            get {
                return ResourceManager.GetString("Argument_InvalidTypeWithPointersNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlapping spans have mismatching alignment..
        /// </summary>
        internal static string Argument_OverlapAlignmentMismatch {
            get {
                return ResourceManager.GetString("Argument_OverlapAlignmentMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision cannot be larger than {0}..
        /// </summary>
        internal static string Argument_PrecisionTooLarge {
            get {
                return ResourceManager.GetString("Argument_PrecisionTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive fallback not allowed for character \\u{0:X4}..
        /// </summary>
        internal static string Argument_RecursiveFallback {
            get {
                return ResourceManager.GetString("Argument_RecursiveFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive fallback not allowed for bytes {0}..
        /// </summary>
        internal static string Argument_RecursiveFallbackBytes {
            get {
                return ResourceManager.GetString("Argument_RecursiveFallbackBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream was not readable.
        /// </summary>
        internal static string Argument_StreamNotReadable {
            get {
                return ResourceManager.GetString("Argument_StreamNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream was not writable..
        /// </summary>
        internal static string Argument_StreamNotWritable {
            get {
                return ResourceManager.GetString("Argument_StreamNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer is not associated with this pool and may not be returned to it..
        /// </summary>
        internal static string ArgumentException_BufferNotFromPool {
            get {
                return ResourceManager.GetString("ArgumentException_BufferNotFromPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many characters. The resulting number of bytes is larger than what can be returned as an int..
        /// </summary>
        internal static string ArgumentOutOfRange_GetByteCountOverflow {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_GetByteCountOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many bytes. The resulting number of chars is larger than what can be returned as an int..
        /// </summary>
        internal static string ArgumentOutOfRange_GetCharCountOverflow {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_GetCharCountOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index and count must refer to a location within the string..
        /// </summary>
        internal static string ArgumentOutOfRange_IndexCount {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index and count must refer to a location within the buffer..
        /// </summary>
        internal static string ArgumentOutOfRange_IndexCountBuffer {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexCountBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be non-negative and less than the size of the collection..
        /// </summary>
        internal static string ArgumentOutOfRange_IndexMustBeLess {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexMustBeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be non-negative and less than or equal to the size of the collection..
        /// </summary>
        internal static string ArgumentOutOfRange_IndexMustBeLessOrEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexMustBeLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-negative number required..
        /// </summary>
        internal static string ArgumentOutOfRange_NeedNonNegNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid values are between {0} and {1}, inclusive..
        /// </summary>
        internal static string ArgumentOutOfRange_Range {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream length must be non-negative and less than 2^31 - 1 - origin..
        /// </summary>
        internal static string ArgumentOutOfRange_StreamLength {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_StreamLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not an array with the same initialization state as the array to compare it to..
        /// </summary>
        internal static string ArrayInitializedStateNotEqual {
            get {
                return ResourceManager.GetString("ArrayInitializedStateNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not an array with the same number of elements as the array to compare it to..
        /// </summary>
        internal static string ArrayLengthsNotEqual {
            get {
                return ResourceManager.GetString("ArrayLengthsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file.  The specified type doesn&apos;t exist..
        /// </summary>
        internal static string BadImageFormat_InvalidType {
            get {
                return ResourceManager.GetString("BadImageFormat_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. String length must be non-negative..
        /// </summary>
        internal static string BadImageFormat_NegativeStringLength {
            get {
                return ResourceManager.GetString("BadImageFormat_NegativeStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file.  The specified data length &apos;{0}&apos; is not a valid position in the stream..
        /// </summary>
        internal static string BadImageFormat_ResourceDataLengthInvalid {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourceDataLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. A resource name extends past the end of the stream..
        /// </summary>
        internal static string BadImageFormat_ResourceNameCorrupted {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourceNameCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. The resource name for name index {0} extends past the end of the stream..
        /// </summary>
        internal static string BadImageFormat_ResourceNameCorrupted_NameIndex {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourceNameCorrupted_NameIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. Invalid offset &apos;{0}&apos; into data section..
        /// </summary>
        internal static string BadImageFormat_ResourcesDataInvalidOffset {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesDataInvalidOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. Unable to read resources from this file because of invalid header information. Try regenerating the .resources file..
        /// </summary>
        internal static string BadImageFormat_ResourcesHeaderCorrupted {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesHeaderCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. String for name index &apos;{0}&apos; extends past the end of the file..
        /// </summary>
        internal static string BadImageFormat_ResourcesIndexTooLong {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesIndexTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. Invalid offset &apos;{0}&apos; into name section..
        /// </summary>
        internal static string BadImageFormat_ResourcesNameInvalidOffset {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesNameInvalidOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. Resource name extends past the end of the file..
        /// </summary>
        internal static string BadImageFormat_ResourcesNameTooLong {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type serialized in the .resources file was not the same type that the .resources file said it contained. Expected &apos;{0}&apos; but read &apos;{1}&apos;..
        /// </summary>
        internal static string BadImageFormat_ResType_SerBlobMismatch {
            get {
                return ResourceManager.GetString("BadImageFormat_ResType_SerBlobMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file.  The specified type doesn&apos;t match the available data in the stream..
        /// </summary>
        internal static string BadImageFormat_TypeMismatch {
            get {
                return ResourceManager.GetString("BadImageFormat_TypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the old value..
        /// </summary>
        internal static string CannotFindOldValue {
            get {
                return ResourceManager.GetString("CannotFindOldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity was less than the current Count of elements..
        /// </summary>
        internal static string CapacityMustBeGreaterThanOrEqualToCount {
            get {
                return ResourceManager.GetString("CapacityMustBeGreaterThanOrEqualToCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveToImmutable can only be performed when Count equals Capacity..
        /// </summary>
        internal static string CapacityMustEqualCountOnMove {
            get {
                return ResourceManager.GetString("CapacityMustEqualCountOnMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection was modified; enumeration operation may not execute..
        /// </summary>
        internal static string CollectionModifiedDuringEnumeration {
            get {
                return ResourceManager.GetString("CollectionModifiedDuringEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element with the same key but a different value already exists. Key: &apos;{0}&apos;.
        /// </summary>
        internal static string DuplicateKey {
            get {
                return ResourceManager.GetString("DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End position was not reached during enumeration..
        /// </summary>
        internal static string EndPositionNotReached {
            get {
                return ResourceManager.GetString("EndPositionNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many bytes in what should have been a 7 bit encoded Int32..
        /// </summary>
        internal static string Format_Bad7BitInt32 {
            get {
                return ResourceManager.GetString("Format_Bad7BitInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western European (Mac).
        /// </summary>
        internal static string Globalization_cp_10000 {
            get {
                return ResourceManager.GetString("Globalization_cp_10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (Mac).
        /// </summary>
        internal static string Globalization_cp_10001 {
            get {
                return ResourceManager.GetString("Globalization_cp_10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Traditional (Mac).
        /// </summary>
        internal static string Globalization_cp_10002 {
            get {
                return ResourceManager.GetString("Globalization_cp_10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean (Mac).
        /// </summary>
        internal static string Globalization_cp_10003 {
            get {
                return ResourceManager.GetString("Globalization_cp_10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic (Mac).
        /// </summary>
        internal static string Globalization_cp_10004 {
            get {
                return ResourceManager.GetString("Globalization_cp_10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew (Mac).
        /// </summary>
        internal static string Globalization_cp_10005 {
            get {
                return ResourceManager.GetString("Globalization_cp_10005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek (Mac).
        /// </summary>
        internal static string Globalization_cp_10006 {
            get {
                return ResourceManager.GetString("Globalization_cp_10006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic (Mac).
        /// </summary>
        internal static string Globalization_cp_10007 {
            get {
                return ResourceManager.GetString("Globalization_cp_10007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified (Mac).
        /// </summary>
        internal static string Globalization_cp_10008 {
            get {
                return ResourceManager.GetString("Globalization_cp_10008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian (Mac).
        /// </summary>
        internal static string Globalization_cp_10010 {
            get {
                return ResourceManager.GetString("Globalization_cp_10010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian (Mac).
        /// </summary>
        internal static string Globalization_cp_10017 {
            get {
                return ResourceManager.GetString("Globalization_cp_10017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai (Mac).
        /// </summary>
        internal static string Globalization_cp_10021 {
            get {
                return ResourceManager.GetString("Globalization_cp_10021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central European (Mac).
        /// </summary>
        internal static string Globalization_cp_10029 {
            get {
                return ResourceManager.GetString("Globalization_cp_10029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelandic (Mac).
        /// </summary>
        internal static string Globalization_cp_10079 {
            get {
                return ResourceManager.GetString("Globalization_cp_10079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish (Mac).
        /// </summary>
        internal static string Globalization_cp_10081 {
            get {
                return ResourceManager.GetString("Globalization_cp_10081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian (Mac).
        /// </summary>
        internal static string Globalization_cp_10082 {
            get {
                return ResourceManager.GetString("Globalization_cp_10082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Turkish Latin-5).
        /// </summary>
        internal static string Globalization_cp_1026 {
            get {
                return ResourceManager.GetString("Globalization_cp_1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM Latin-1.
        /// </summary>
        internal static string Globalization_cp_1047 {
            get {
                return ResourceManager.GetString("Globalization_cp_1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (US-Canada-Euro).
        /// </summary>
        internal static string Globalization_cp_1140 {
            get {
                return ResourceManager.GetString("Globalization_cp_1140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Germany-Euro).
        /// </summary>
        internal static string Globalization_cp_1141 {
            get {
                return ResourceManager.GetString("Globalization_cp_1141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Denmark-Norway-Euro).
        /// </summary>
        internal static string Globalization_cp_1142 {
            get {
                return ResourceManager.GetString("Globalization_cp_1142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Finland-Sweden-Euro).
        /// </summary>
        internal static string Globalization_cp_1143 {
            get {
                return ResourceManager.GetString("Globalization_cp_1143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Italy-Euro).
        /// </summary>
        internal static string Globalization_cp_1144 {
            get {
                return ResourceManager.GetString("Globalization_cp_1144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Spain-Euro).
        /// </summary>
        internal static string Globalization_cp_1145 {
            get {
                return ResourceManager.GetString("Globalization_cp_1145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (UK-Euro).
        /// </summary>
        internal static string Globalization_cp_1146 {
            get {
                return ResourceManager.GetString("Globalization_cp_1146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (France-Euro).
        /// </summary>
        internal static string Globalization_cp_1147 {
            get {
                return ResourceManager.GetString("Globalization_cp_1147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (International-Euro).
        /// </summary>
        internal static string Globalization_cp_1148 {
            get {
                return ResourceManager.GetString("Globalization_cp_1148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Icelandic-Euro).
        /// </summary>
        internal static string Globalization_cp_1149 {
            get {
                return ResourceManager.GetString("Globalization_cp_1149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central European (Windows).
        /// </summary>
        internal static string Globalization_cp_1250 {
            get {
                return ResourceManager.GetString("Globalization_cp_1250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic (Windows).
        /// </summary>
        internal static string Globalization_cp_1251 {
            get {
                return ResourceManager.GetString("Globalization_cp_1251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western European (Windows).
        /// </summary>
        internal static string Globalization_cp_1252 {
            get {
                return ResourceManager.GetString("Globalization_cp_1252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek (Windows).
        /// </summary>
        internal static string Globalization_cp_1253 {
            get {
                return ResourceManager.GetString("Globalization_cp_1253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish (Windows).
        /// </summary>
        internal static string Globalization_cp_1254 {
            get {
                return ResourceManager.GetString("Globalization_cp_1254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew (Windows).
        /// </summary>
        internal static string Globalization_cp_1255 {
            get {
                return ResourceManager.GetString("Globalization_cp_1255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic (Windows).
        /// </summary>
        internal static string Globalization_cp_1256 {
            get {
                return ResourceManager.GetString("Globalization_cp_1256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baltic (Windows).
        /// </summary>
        internal static string Globalization_cp_1257 {
            get {
                return ResourceManager.GetString("Globalization_cp_1257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese (Windows).
        /// </summary>
        internal static string Globalization_cp_1258 {
            get {
                return ResourceManager.GetString("Globalization_cp_1258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean (Johab).
        /// </summary>
        internal static string Globalization_cp_1361 {
            get {
                return ResourceManager.GetString("Globalization_cp_1361", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Traditional (CNS).
        /// </summary>
        internal static string Globalization_cp_20000 {
            get {
                return ResourceManager.GetString("Globalization_cp_20000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCA Taiwan.
        /// </summary>
        internal static string Globalization_cp_20001 {
            get {
                return ResourceManager.GetString("Globalization_cp_20001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Traditional (Eten).
        /// </summary>
        internal static string Globalization_cp_20002 {
            get {
                return ResourceManager.GetString("Globalization_cp_20002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM5550 Taiwan.
        /// </summary>
        internal static string Globalization_cp_20003 {
            get {
                return ResourceManager.GetString("Globalization_cp_20003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeleText Taiwan.
        /// </summary>
        internal static string Globalization_cp_20004 {
            get {
                return ResourceManager.GetString("Globalization_cp_20004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wang Taiwan.
        /// </summary>
        internal static string Globalization_cp_20005 {
            get {
                return ResourceManager.GetString("Globalization_cp_20005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western European (IA5).
        /// </summary>
        internal static string Globalization_cp_20105 {
            get {
                return ResourceManager.GetString("Globalization_cp_20105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (IA5).
        /// </summary>
        internal static string Globalization_cp_20106 {
            get {
                return ResourceManager.GetString("Globalization_cp_20106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish (IA5).
        /// </summary>
        internal static string Globalization_cp_20107 {
            get {
                return ResourceManager.GetString("Globalization_cp_20107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian (IA5).
        /// </summary>
        internal static string Globalization_cp_20108 {
            get {
                return ResourceManager.GetString("Globalization_cp_20108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.61.
        /// </summary>
        internal static string Globalization_cp_20261 {
            get {
                return ResourceManager.GetString("Globalization_cp_20261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO-6937.
        /// </summary>
        internal static string Globalization_cp_20269 {
            get {
                return ResourceManager.GetString("Globalization_cp_20269", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Germany).
        /// </summary>
        internal static string Globalization_cp_20273 {
            get {
                return ResourceManager.GetString("Globalization_cp_20273", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Denmark-Norway).
        /// </summary>
        internal static string Globalization_cp_20277 {
            get {
                return ResourceManager.GetString("Globalization_cp_20277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Finland-Sweden).
        /// </summary>
        internal static string Globalization_cp_20278 {
            get {
                return ResourceManager.GetString("Globalization_cp_20278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Italy).
        /// </summary>
        internal static string Globalization_cp_20280 {
            get {
                return ResourceManager.GetString("Globalization_cp_20280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Spain).
        /// </summary>
        internal static string Globalization_cp_20284 {
            get {
                return ResourceManager.GetString("Globalization_cp_20284", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (UK).
        /// </summary>
        internal static string Globalization_cp_20285 {
            get {
                return ResourceManager.GetString("Globalization_cp_20285", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Japanese katakana).
        /// </summary>
        internal static string Globalization_cp_20290 {
            get {
                return ResourceManager.GetString("Globalization_cp_20290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (France).
        /// </summary>
        internal static string Globalization_cp_20297 {
            get {
                return ResourceManager.GetString("Globalization_cp_20297", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Arabic).
        /// </summary>
        internal static string Globalization_cp_20420 {
            get {
                return ResourceManager.GetString("Globalization_cp_20420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Greek).
        /// </summary>
        internal static string Globalization_cp_20423 {
            get {
                return ResourceManager.GetString("Globalization_cp_20423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Hebrew).
        /// </summary>
        internal static string Globalization_cp_20424 {
            get {
                return ResourceManager.GetString("Globalization_cp_20424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Korean Extended).
        /// </summary>
        internal static string Globalization_cp_20833 {
            get {
                return ResourceManager.GetString("Globalization_cp_20833", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Thai).
        /// </summary>
        internal static string Globalization_cp_20838 {
            get {
                return ResourceManager.GetString("Globalization_cp_20838", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic (KOI8-R).
        /// </summary>
        internal static string Globalization_cp_20866 {
            get {
                return ResourceManager.GetString("Globalization_cp_20866", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Icelandic).
        /// </summary>
        internal static string Globalization_cp_20871 {
            get {
                return ResourceManager.GetString("Globalization_cp_20871", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Cyrillic Russian).
        /// </summary>
        internal static string Globalization_cp_20880 {
            get {
                return ResourceManager.GetString("Globalization_cp_20880", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Turkish).
        /// </summary>
        internal static string Globalization_cp_20905 {
            get {
                return ResourceManager.GetString("Globalization_cp_20905", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM Latin-1.
        /// </summary>
        internal static string Globalization_cp_20924 {
            get {
                return ResourceManager.GetString("Globalization_cp_20924", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (JIS 0208-1990 and 0212-1990).
        /// </summary>
        internal static string Globalization_cp_20932 {
            get {
                return ResourceManager.GetString("Globalization_cp_20932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified (GB2312-80).
        /// </summary>
        internal static string Globalization_cp_20936 {
            get {
                return ResourceManager.GetString("Globalization_cp_20936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean Wansung.
        /// </summary>
        internal static string Globalization_cp_20949 {
            get {
                return ResourceManager.GetString("Globalization_cp_20949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Cyrillic Serbian-Bulgarian).
        /// </summary>
        internal static string Globalization_cp_21025 {
            get {
                return ResourceManager.GetString("Globalization_cp_21025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext Alpha Lowercase.
        /// </summary>
        internal static string Globalization_cp_21027 {
            get {
                return ResourceManager.GetString("Globalization_cp_21027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic (KOI8-U).
        /// </summary>
        internal static string Globalization_cp_21866 {
            get {
                return ResourceManager.GetString("Globalization_cp_21866", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central European (ISO).
        /// </summary>
        internal static string Globalization_cp_28592 {
            get {
                return ResourceManager.GetString("Globalization_cp_28592", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin 3 (ISO).
        /// </summary>
        internal static string Globalization_cp_28593 {
            get {
                return ResourceManager.GetString("Globalization_cp_28593", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baltic (ISO).
        /// </summary>
        internal static string Globalization_cp_28594 {
            get {
                return ResourceManager.GetString("Globalization_cp_28594", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic (ISO).
        /// </summary>
        internal static string Globalization_cp_28595 {
            get {
                return ResourceManager.GetString("Globalization_cp_28595", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic (ISO).
        /// </summary>
        internal static string Globalization_cp_28596 {
            get {
                return ResourceManager.GetString("Globalization_cp_28596", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek (ISO).
        /// </summary>
        internal static string Globalization_cp_28597 {
            get {
                return ResourceManager.GetString("Globalization_cp_28597", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew (ISO-Visual).
        /// </summary>
        internal static string Globalization_cp_28598 {
            get {
                return ResourceManager.GetString("Globalization_cp_28598", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish (ISO).
        /// </summary>
        internal static string Globalization_cp_28599 {
            get {
                return ResourceManager.GetString("Globalization_cp_28599", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian (ISO).
        /// </summary>
        internal static string Globalization_cp_28603 {
            get {
                return ResourceManager.GetString("Globalization_cp_28603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin 9 (ISO).
        /// </summary>
        internal static string Globalization_cp_28605 {
            get {
                return ResourceManager.GetString("Globalization_cp_28605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europa.
        /// </summary>
        internal static string Globalization_cp_29001 {
            get {
                return ResourceManager.GetString("Globalization_cp_29001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (US-Canada).
        /// </summary>
        internal static string Globalization_cp_37 {
            get {
                return ResourceManager.GetString("Globalization_cp_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew (ISO-Logical).
        /// </summary>
        internal static string Globalization_cp_38598 {
            get {
                return ResourceManager.GetString("Globalization_cp_38598", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM United States.
        /// </summary>
        internal static string Globalization_cp_437 {
            get {
                return ResourceManager.GetString("Globalization_cp_437", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (International).
        /// </summary>
        internal static string Globalization_cp_500 {
            get {
                return ResourceManager.GetString("Globalization_cp_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined.
        /// </summary>
        internal static string Globalization_cp_50000 {
            get {
                return ResourceManager.GetString("Globalization_cp_50000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (JIS).
        /// </summary>
        internal static string Globalization_cp_50220 {
            get {
                return ResourceManager.GetString("Globalization_cp_50220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (JIS-Allow 1 byte Kana).
        /// </summary>
        internal static string Globalization_cp_50221 {
            get {
                return ResourceManager.GetString("Globalization_cp_50221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (JIS-Allow 1 byte Kana - SO/SI).
        /// </summary>
        internal static string Globalization_cp_50222 {
            get {
                return ResourceManager.GetString("Globalization_cp_50222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean (ISO).
        /// </summary>
        internal static string Globalization_cp_50225 {
            get {
                return ResourceManager.GetString("Globalization_cp_50225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified (ISO-2022).
        /// </summary>
        internal static string Globalization_cp_50227 {
            get {
                return ResourceManager.GetString("Globalization_cp_50227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Traditional (ISO-2022).
        /// </summary>
        internal static string Globalization_cp_50229 {
            get {
                return ResourceManager.GetString("Globalization_cp_50229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Japanese and Japanese Katakana).
        /// </summary>
        internal static string Globalization_cp_50930 {
            get {
                return ResourceManager.GetString("Globalization_cp_50930", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Japanese and US-Canada).
        /// </summary>
        internal static string Globalization_cp_50931 {
            get {
                return ResourceManager.GetString("Globalization_cp_50931", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Korean and Korean Extended).
        /// </summary>
        internal static string Globalization_cp_50933 {
            get {
                return ResourceManager.GetString("Globalization_cp_50933", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Simplified Chinese).
        /// </summary>
        internal static string Globalization_cp_50935 {
            get {
                return ResourceManager.GetString("Globalization_cp_50935", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Traditional Chinese).
        /// </summary>
        internal static string Globalization_cp_50937 {
            get {
                return ResourceManager.GetString("Globalization_cp_50937", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Japanese and Japanese-Latin).
        /// </summary>
        internal static string Globalization_cp_50939 {
            get {
                return ResourceManager.GetString("Globalization_cp_50939", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (EUC).
        /// </summary>
        internal static string Globalization_cp_51932 {
            get {
                return ResourceManager.GetString("Globalization_cp_51932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified (EUC).
        /// </summary>
        internal static string Globalization_cp_51936 {
            get {
                return ResourceManager.GetString("Globalization_cp_51936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean (EUC).
        /// </summary>
        internal static string Globalization_cp_51949 {
            get {
                return ResourceManager.GetString("Globalization_cp_51949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified (HZ).
        /// </summary>
        internal static string Globalization_cp_52936 {
            get {
                return ResourceManager.GetString("Globalization_cp_52936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified (GB18030).
        /// </summary>
        internal static string Globalization_cp_54936 {
            get {
                return ResourceManager.GetString("Globalization_cp_54936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Devanagari.
        /// </summary>
        internal static string Globalization_cp_57002 {
            get {
                return ResourceManager.GetString("Globalization_cp_57002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Bengali.
        /// </summary>
        internal static string Globalization_cp_57003 {
            get {
                return ResourceManager.GetString("Globalization_cp_57003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Tamil.
        /// </summary>
        internal static string Globalization_cp_57004 {
            get {
                return ResourceManager.GetString("Globalization_cp_57004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Telugu.
        /// </summary>
        internal static string Globalization_cp_57005 {
            get {
                return ResourceManager.GetString("Globalization_cp_57005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Assamese.
        /// </summary>
        internal static string Globalization_cp_57006 {
            get {
                return ResourceManager.GetString("Globalization_cp_57006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Oriya.
        /// </summary>
        internal static string Globalization_cp_57007 {
            get {
                return ResourceManager.GetString("Globalization_cp_57007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Kannada.
        /// </summary>
        internal static string Globalization_cp_57008 {
            get {
                return ResourceManager.GetString("Globalization_cp_57008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Malayalam.
        /// </summary>
        internal static string Globalization_cp_57009 {
            get {
                return ResourceManager.GetString("Globalization_cp_57009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Gujarati.
        /// </summary>
        internal static string Globalization_cp_57010 {
            get {
                return ResourceManager.GetString("Globalization_cp_57010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Punjabi.
        /// </summary>
        internal static string Globalization_cp_57011 {
            get {
                return ResourceManager.GetString("Globalization_cp_57011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic (ASMO 708).
        /// </summary>
        internal static string Globalization_cp_708 {
            get {
                return ResourceManager.GetString("Globalization_cp_708", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic (DOS).
        /// </summary>
        internal static string Globalization_cp_720 {
            get {
                return ResourceManager.GetString("Globalization_cp_720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek (DOS).
        /// </summary>
        internal static string Globalization_cp_737 {
            get {
                return ResourceManager.GetString("Globalization_cp_737", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baltic (DOS).
        /// </summary>
        internal static string Globalization_cp_775 {
            get {
                return ResourceManager.GetString("Globalization_cp_775", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western European (DOS).
        /// </summary>
        internal static string Globalization_cp_850 {
            get {
                return ResourceManager.GetString("Globalization_cp_850", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central European (DOS).
        /// </summary>
        internal static string Globalization_cp_852 {
            get {
                return ResourceManager.GetString("Globalization_cp_852", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM Cyrillic.
        /// </summary>
        internal static string Globalization_cp_855 {
            get {
                return ResourceManager.GetString("Globalization_cp_855", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish (DOS).
        /// </summary>
        internal static string Globalization_cp_857 {
            get {
                return ResourceManager.GetString("Globalization_cp_857", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM Multilingual Latin I.
        /// </summary>
        internal static string Globalization_cp_858 {
            get {
                return ResourceManager.GetString("Globalization_cp_858", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (DOS).
        /// </summary>
        internal static string Globalization_cp_860 {
            get {
                return ResourceManager.GetString("Globalization_cp_860", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelandic (DOS).
        /// </summary>
        internal static string Globalization_cp_861 {
            get {
                return ResourceManager.GetString("Globalization_cp_861", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew (DOS).
        /// </summary>
        internal static string Globalization_cp_862 {
            get {
                return ResourceManager.GetString("Globalization_cp_862", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Canadian (DOS).
        /// </summary>
        internal static string Globalization_cp_863 {
            get {
                return ResourceManager.GetString("Globalization_cp_863", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic (864).
        /// </summary>
        internal static string Globalization_cp_864 {
            get {
                return ResourceManager.GetString("Globalization_cp_864", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nordic (DOS).
        /// </summary>
        internal static string Globalization_cp_865 {
            get {
                return ResourceManager.GetString("Globalization_cp_865", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic (DOS).
        /// </summary>
        internal static string Globalization_cp_866 {
            get {
                return ResourceManager.GetString("Globalization_cp_866", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek, Modern (DOS).
        /// </summary>
        internal static string Globalization_cp_869 {
            get {
                return ResourceManager.GetString("Globalization_cp_869", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Multilingual Latin-2).
        /// </summary>
        internal static string Globalization_cp_870 {
            get {
                return ResourceManager.GetString("Globalization_cp_870", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai (Windows).
        /// </summary>
        internal static string Globalization_cp_874 {
            get {
                return ResourceManager.GetString("Globalization_cp_874", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Greek Modern).
        /// </summary>
        internal static string Globalization_cp_875 {
            get {
                return ResourceManager.GetString("Globalization_cp_875", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (Shift-JIS).
        /// </summary>
        internal static string Globalization_cp_932 {
            get {
                return ResourceManager.GetString("Globalization_cp_932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified (GB2312).
        /// </summary>
        internal static string Globalization_cp_936 {
            get {
                return ResourceManager.GetString("Globalization_cp_936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string Globalization_cp_949 {
            get {
                return ResourceManager.GetString("Globalization_cp_949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Traditional (Big5).
        /// </summary>
        internal static string Globalization_cp_950 {
            get {
                return ResourceManager.GetString("Globalization_cp_950", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Information2 {
            get {
                object obj = ResourceManager.GetObject("Information2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation does not apply to an empty instance..
        /// </summary>
        internal static string InvalidEmptyOperation {
            get {
                return ResourceManager.GetString("InvalidEmptyOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon InvalidOperation {
            get {
                object obj = ResourceManager.GetObject("InvalidOperation", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration already finished..
        /// </summary>
        internal static string InvalidOperation_EnumEnded {
            get {
                return ResourceManager.GetString("InvalidOperation_EnumEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration has not started. Call MoveNext..
        /// </summary>
        internal static string InvalidOperation_EnumNotStarted {
            get {
                return ResourceManager.GetString("InvalidOperation_EnumNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; was not a Stream - call GetObject instead..
        /// </summary>
        internal static string InvalidOperation_ResourceNotStream_Name {
            get {
                return ResourceManager.GetString("InvalidOperation_ResourceNotStream_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; was not a String - call GetObject instead..
        /// </summary>
        internal static string InvalidOperation_ResourceNotString_Name {
            get {
                return ResourceManager.GetString("InvalidOperation_ResourceNotString_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource was of type &apos;{0}&apos; instead of String - call GetObject instead..
        /// </summary>
        internal static string InvalidOperation_ResourceNotString_Type {
            get {
                return ResourceManager.GetString("InvalidOperation_ResourceNotString_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource writer has already been closed and cannot be edited..
        /// </summary>
        internal static string InvalidOperation_ResourceWriterSaved {
            get {
                return ResourceManager.GetString("InvalidOperation_ResourceWriterSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be performed on a default instance of ImmutableArray&lt;T&gt;.  Consider initializing the array, or checking the ImmutableArray&lt;T&gt;.IsDefault property..
        /// </summary>
        internal static string InvalidOperationOnDefaultArray {
            get {
                return ResourceManager.GetString("InvalidOperationOnDefaultArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms-actionbar://.
        /// </summary>
        internal static string MDCFR_LINK_ACTIONBAR {
            get {
                return ResourceManager.GetString("MDCFR_LINK_ACTIONBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms-actioncenter:controlcenter/&amp;suppressAnimations=false&amp;showFooter=true&amp;allowPageNavigation=true&amp;edgeGestureOffset=0&amp;inputAnimationSourceId=0&amp;inputAnimationProviderId=0.
        /// </summary>
        internal static string MDCFR_LINK_ACTIONBAR2 {
            get {
                return ResourceManager.GetString("MDCFR_LINK_ACTIONBAR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms-calculator://.
        /// </summary>
        internal static string MDCFR_LINK_CALC {
            get {
                return ResourceManager.GetString("MDCFR_LINK_CALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outlookcal://.
        /// </summary>
        internal static string MDCFR_LINK_CALENDAR {
            get {
                return ResourceManager.GetString("MDCFR_LINK_CALENDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to microsoft.windows.camera://.
        /// </summary>
        internal static string MDCFR_LINK_CAMERA {
            get {
                return ResourceManager.GetString("MDCFR_LINK_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms-clock://.
        /// </summary>
        internal static string MDCFR_LINK_CLOCK {
            get {
                return ResourceManager.GetString("MDCFR_LINK_CLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms-wxh://.
        /// </summary>
        internal static string MDCFR_LINK_GETSTARTED {
            get {
                return ResourceManager.GetString("MDCFR_LINK_GETSTARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outlookmail://.
        /// </summary>
        internal static string MDCFR_LINK_MAIL {
            get {
                return ResourceManager.GetString("MDCFR_LINK_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bingmaps://.
        /// </summary>
        internal static string MDCFR_LINK_MAPS {
            get {
                return ResourceManager.GetString("MDCFR_LINK_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mswindowsmusic://.
        /// </summary>
        internal static string MDCFR_LINK_MUSIC {
            get {
                return ResourceManager.GetString("MDCFR_LINK_MUSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms-officeapp://.
        /// </summary>
        internal static string MDCFR_LINK_OFFICE {
            get {
                return ResourceManager.GetString("MDCFR_LINK_OFFICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms-people://.
        /// </summary>
        internal static string MDCFR_LINK_PEOPLE {
            get {
                return ResourceManager.GetString("MDCFR_LINK_PEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms-phone://.
        /// </summary>
        internal static string MDCFR_LINK_PHONELINK {
            get {
                return ResourceManager.GetString("MDCFR_LINK_PHONELINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms-photos://.
        /// </summary>
        internal static string MDCFR_LINK_PHOTOS {
            get {
                return ResourceManager.GetString("MDCFR_LINK_PHOTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms-screenclip://.
        /// </summary>
        internal static string MDCFR_LINK_SCREENCLIP {
            get {
                return ResourceManager.GetString("MDCFR_LINK_SCREENCLIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zune://.
        /// </summary>
        internal static string MDCFR_LINK_STORE {
            get {
                return ResourceManager.GetString("MDCFR_LINK_STORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms-get-started://.
        /// </summary>
        internal static string MDCFR_LINK_TIPS {
            get {
                return ResourceManager.GetString("MDCFR_LINK_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to windowsdefender://.
        /// </summary>
        internal static string MDCFR_LINK_WINDEFENDER {
            get {
                return ResourceManager.GetString("MDCFR_LINK_WINDEFENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms-settings://.
        /// </summary>
        internal static string MDCFR_LINK_WINSETTINGS {
            get {
                return ResourceManager.GetString("MDCFR_LINK_WINSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory&lt;T&gt; has been disposed..
        /// </summary>
        internal static string MemoryDisposed {
            get {
                return ResourceManager.GetString("MemoryDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a resource entry for the encoding codepage &apos;{0} - {1}&apos;.
        /// </summary>
        internal static string MissingEncodingNameResource {
            get {
                return ResourceManager.GetString("MissingEncodingNameResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This platform does not support binary serialized resources..
        /// </summary>
        internal static string NotSupported_BinarySerializedResources {
            get {
                return ResourceManager.GetString("NotSupported_BinarySerializedResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals() on Span and ReadOnlySpan is not supported. Use operator== instead..
        /// </summary>
        internal static string NotSupported_CannotCallEqualsOnSpan {
            get {
                return ResourceManager.GetString("NotSupported_CannotCallEqualsOnSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetHashCode() on Span and ReadOnlySpan is not supported..
        /// </summary>
        internal static string NotSupported_CannotCallGetHashCodeOnSpan {
            get {
                return ResourceManager.GetString("NotSupported_CannotCallGetHashCodeOnSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data is available for encoding {0}..
        /// </summary>
        internal static string NotSupported_NoCodepageData {
            get {
                return ResourceManager.GetString("NotSupported_NoCodepageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read resources that depend on serialization..
        /// </summary>
        internal static string NotSupported_ResourceObjectSerialization {
            get {
                return ResourceManager.GetString("NotSupported_ResourceObjectSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support seeking..
        /// </summary>
        internal static string NotSupported_UnseekableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnseekableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This .resources file should not be read with this reader. The resource reader type is &quot;{0}&quot;..
        /// </summary>
        internal static string NotSupported_WrongResourceReader_Type {
            get {
                return ResourceManager.GetString("NotSupported_WrongResourceReader_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a closed resource set..
        /// </summary>
        internal static string ObjectDisposed_ResourceSet {
            get {
                return ResourceManager.GetString("ObjectDisposed_ResourceSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release all references before disposing this instance..
        /// </summary>
        internal static string OutstandingReferences {
            get {
                return ResourceManager.GetString("OutstandingReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Question {
            get {
                object obj = ResourceManager.GetObject("Question", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of ResourceManager for custom types is disabled. Set the MSBuild Property CustomResourceTypesSupport to true in order to enable it..
        /// </summary>
        internal static string ResourceManager_ReflectionNotAllowed {
            get {
                return ResourceManager.GetString("ResourceManager_ReflectionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceReader is closed..
        /// </summary>
        internal static string ResourceReaderIsClosed {
            get {
                return ResourceManager.GetString("ResourceReaderIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is not a valid resource file..
        /// </summary>
        internal static string Resources_StreamNotValid {
            get {
                return ResourceManager.GetString("Resources_StreamNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load a converter for type {0}..
        /// </summary>
        internal static string TypeLoadException_CannotLoadConverter {
            get {
                return ResourceManager.GetString("TypeLoadException_CannotLoadConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected segment type..
        /// </summary>
        internal static string UnexpectedSegmentType {
            get {
                return ResourceManager.GetString("UnexpectedSegmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
