/*
	Do not edit this file directly. This file defines the assembly metadata and should not be modified
	at any case except if it is needed.
*/

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyCompanyAttribute($"© MDCDI1315. {mdcdi1315.SourceLink}")]
[assembly: AssemblyCopyrightAttribute(mdcdi1315.Copyright)]
[assembly: AssemblyDescriptionAttribute(mdcdi1315.Description)]
[assembly: AssemblyFileVersionAttribute(mdcdi1315.VersionNumber)]
[assembly: AssemblyInformationalVersionAttribute($"{mdcdi1315.VersionNumber} Built by: © MDCDI1315.")]
[assembly: AssemblyProductAttribute($"{mdcdi1315.Product} , Version 1.5.5.0 Minor 5")]
[assembly: AssemblyVersionAttribute("4.4.0.0")]
#if DEBUG
    [assembly: AssemblyTitleAttribute("Interface Reference Attribute Checker (Debug Flavor)")]
    [assembly: AssemblyConfigurationAttribute("Debug")]
#else
    [assembly: AssemblyTitleAttribute("Interface Reference Attribute Checker")]
    [assembly: AssemblyConfigurationAttribute("Release")]
#endif
[assembly: AssemblyMetadataAttribute("FrameworkDisplayName (FDN Internal)" , ".NET Framework 4.8")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]


/// <summary>
/// An internal class defining the author's reserved strings.
/// </summary>
[System.Runtime.CompilerServices.SpecialName]
[System.Runtime.CompilerServices.CompilerGlobalScope]
internal static class mdcdi1315
{
    /// <summary>
    /// An internal string defining the current product.
    /// </summary>
    public const System.String Product = "MDC Application Framework";

    /// <summary>
    /// An internal string defining the author of the product.
    /// </summary>
    public const System.String Author = "mdcdi1315";

    /// <summary>
    /// A link to the Author Account in GitHub.
    /// </summary>
    public const System.String AuthorLinkGitHub = $"http://github.com/{Author}";

    /// <summary>
    /// A small description of this product.
    /// </summary>
    public const System.String Description = "Portable Application Development Framework";

    /// <summary>
    /// The Copyright of the current product.
    /// </summary>
    public const System.String Copyright = "© MDCDI1315. All Rights Reserved.";

    /// <summary>
    /// A URL link which mentions the source code repository.
    /// </summary>
    public const System.String SourceLink = $"http://github.com/{Author}/mdcframework";

    /// <summary>
    /// The current version of this tool .
    /// </summary>
    public const System.String VersionNumber = "1.0.0.1";

    /// <summary>
    /// This is the result of the bit-wise combination of <see cref="DllImportSearchPath.AssemblyDirectory"/> and <see cref="DllImportSearchPath.System32"/> enumeration values.
    /// </summary>
    public const System.Int32 DefaultDllImportSearchPathConst = 2050;
}