# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup and prepare .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore MDCFR.dll dependencies
      run: dotnet restore --verbosity normal
    - name: Attempt to build the MDCFR.dll
      run: dotnet build --verbosity normal --configuration Release --no-restore
    - name: Test the output MDCFR.dll with "dotnet test" for IL errors
      run: dotnet test --os Windows --verbosity normal --no-build
