# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: internalhost



    env:
      NUGET_PACKAGES: ${{ github.workspace }}\.nuget\packages
    steps:
    - uses: actions/checkout@v3
    - name: Setup and prepare .NET
      run: D:\DOTNET.cmd -version 7.0
    - name: Restore MDCFR.dll dependencies
      run: dotnet restore --verbosity normal
    - name: Attempt to build the MDCFR.dll
      run: dotnet build --verbosity normal --configuration Release --no-restore
    - name: Test the output MDCFR.dll with "dotnet test" for IL errors
      run: dotnet test --os Windows --verbosity normal --no-build




